version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - docs

linters:
  # Enable specific linters
  enable:
    # Default linters (always good to have)
    - errcheck     # Check for unchecked errors
    - ineffassign  # Detect unused assignments
    - staticcheck  # Staticcheck rules
    - unused       # Find unused code
    
    # Additional quality linters
    - bodyclose    # Check HTTP response body is closed
    - dogsled      # Check for too many blank identifiers
    - dupl         # Find duplicate code
    - exhaustive   # Check exhaustiveness of enum switches
    - misspell     # Find misspelled words
    - nakedret     # Find naked returns
    - prealloc     # Find slice declarations that could be preallocated
    - unconvert    # Find unnecessary type conversions
    
    # Security
    - gosec        # Security checks
    
  disable-all: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Too many false positives with this
    
  exhaustive:
    default-signifies-exhaustive: true
    
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy
      
  misspell:
    locale: US
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
    
  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G307  # Deferring unsafe methods
      
  dupl:
    threshold: 150

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 500
  
  # Maximum count of issues with the same text
  max-same-issues: 50
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck
        
    # Temporarily ignore typecheck errors in connector files
    - path: pkg/connector/.*\.go
      text: "no errors"
      linters:
        - typecheck
        
    # Exclude some linters from generated files
    - path: _gen\.go
      linters:
        - unused
        - dupl
        
    # Exclude known issues we'll fix later
    - path: cmd/
      linters:
        - errcheck  # CLI tools often don't check all errors
        
    - path: examples/
      linters:
        - errcheck
        - unused
        
  # Exclude some well-known issues
  exclude:
    # Go 1.25.0 bug: outputs "no errors" to stderr for successful builds
    - "no errors"
    # errcheck: Almost all programs ignore errors on these functions
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    
    # golint: Exported types in internal packages don't need comments
    - exported .* should have comment
    
    # gosec: Often not practical in server code
    - Potential hardcoded credentials