name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Run tests
      run: make test

    - name: Build binaries
      run: |
        make build
        GOOS=linux GOARCH=amd64 go build -o bin/nebula-linux-amd64 ./cmd/nebula/
        GOOS=linux GOARCH=arm64 go build -o bin/nebula-linux-arm64 ./cmd/nebula/
        GOOS=darwin GOARCH=amd64 go build -o bin/nebula-darwin-amd64 ./cmd/nebula/
        GOOS=darwin GOARCH=arm64 go build -o bin/nebula-darwin-arm64 ./cmd/nebula/
        GOOS=windows GOARCH=amd64 go build -o bin/nebula-windows-amd64.exe ./cmd/nebula/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/nebula-linux-amd64
          bin/nebula-linux-arm64
          bin/nebula-darwin-amd64
          bin/nebula-darwin-arm64
          bin/nebula-windows-amd64.exe
        generate_release_notes: true
        draft: false
        prerelease: false